const AccEquipAPI = [
  {
    id: 1,
    image: "/Images/Accessories/accessories (1).jpg",
    price: 992,
    title: "Accessories & Equipments",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    category: "featured",
    gender: "men",
    productName: "acc",
  },
  {
    id: 2,
    image: "/Images/Accessories/accessories (2).jpg",
    price: 932,
    title: "Accessories & Equipments",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    category: "new",
    gender: "kids",
    productName: "acc",
  },
  {
    id: 3,
    image: "/Images/Accessories/accessories (3).jpg",
    price: 600,
    title: "Accessories & Equipments",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    category: "new",
    gender: "women",
    productName: "acc",
  },
  {
    id: 4,
    image: "/Images/Accessories/accessories (4).jpg",
    price: 234,
    title: "Accessories & Equipments",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    category: "new",
    gender: "kids",
    productName: "acc",
  },
  {
    id: 5,
    image: "/Images/Accessories/accessories (5).jpg",
    price: 1544,
    title: "Accessories & Equipments",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    category: "Old_featured",
    gender: "kids",
    productName: "acc",
  },
  {
    id: 6,
    image: "/Images/Accessories/accessories (6).jpg",
    price: 200,
    title: "Accessories & Equipments",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    category: "Old_featured",
    gender: "men",
    productName: "acc",
  },
];

export default AccEquipAPI;
