const FootballAPI = [
  {
    id: 7,
    image: "/Images/Studs/FootballShoes (1).jpg",
    price: 2222,
    title: "Football Shoes",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    category: "featured",
    gender: "men",
    productName: "footballShoes",
  },
  {
    id: 8,
    image: "/Images/Studs/FootballShoes (2).jpg",
    price: 9132,
    title: "Football Shoes",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    category: "new",
    gender: "kids",
    productName: "footballShoes",
  },
  {
    id: 9,
    image: "/Images/Studs/FootballShoes (3).jpg",
    price: 1220,
    title: "Football Shoes",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    category: "new",
    gender: "women",
    productName: "footballShoes",
  },
  {
    id: 10,
    image: "/Images/Studs/FootballShoes (4).jpg",
    price: 3000,
    title: "Football Shoes",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    category: "new",
    gender: "kids",
    productName: "footballShoes",
  },
  {
    id: 11,
    image: "/Images/Studs/FootballShoes (5).jpg",
    price: 1511,
    title: "Football Shoes",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    category: "Old_featured",
    gender: "kids",
    productName: "footballShoes",
  },
  {
    id: 12,
    image: "/Images/Studs/FootballShoes (6).jpg",
    price: 2000,
    title: "Football Shoes",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    category: "Old_featured",
    gender: "men",
    productName: "footballShoes",
  },
];

export default FootballAPI;
