const HoodiesSweatshirtAPI = [
  {
    id: 13,
    image: "/Images/HoodiesSweatshirts/hoodies (1).jpg",
    price: 992,
    title: "Hoodies",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    category: "featured",
    gender: "men",
    productName: "hoodiesSweatshirts",
  },
  {
    id: 14,
    image: "/Images/HoodiesSweatshirts/hoodies (2).jpg",
    price: 999,
    title: "Hoodies",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    category: "new",
    gender: "kids",
    productName: "hoodiesSweatshirts",
  },
  {
    id: 15,
    image: "/Images/HoodiesSweatshirts/women hoodies (1).jpg",
    price: 900,
    title: "Hoodies",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    category: "new",
    gender: "women",
    productName: "hoodiesSweatshirts",
  },
  {
    id: 16,
    image: "/Images/HoodiesSweatshirts/women hoodies (2).jpg",
    price: 900,
    title: "Hoodies",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    category: "new",
    gender: "women",
    productName: "hoodiesSweatshirts",
  },
  {
    id: 17,
    image: "/Images/HoodiesSweatshirts/women hoodies (3).jpg",
    price: 654,
    title: "Hoodies",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    category: "new",
    gender: "women",
    productName: "hoodiesSweatshirts",
  },
  {
    id: 18,
    image: "/Images/HoodiesSweatshirts/women hoodies (4).jpg",
    price: 888,
    title: "Hoodies",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    category: "new",
    gender: "women",
    productName: "hoodiesSweatshirts",
  },
  {
    id: 19,
    image: "/Images/HoodiesSweatshirts/sweatshirts (1).jpg",
    price: 999,
    title: "Sweatshirts",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    category: "new",
    gender: "kids",
    productName: "hoodiesSweatshirts",
  },
  {
    id: 20,
    image: "/Images/HoodiesSweatshirts/sweatshirts (2).jpg",
    price: 154,
    title: "Sweatshirts",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    category: "Old_featured",
    gender: "kids",
    productName: "hoodiesSweatshirts",
  },
  {
    id: 21,
    image: "/Images/HoodiesSweatshirts/sweatshirts (3).jpg",
    price: 200,
    title: "Sweatshirts",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    category: "Old_featured",
    gender: "men",
    productName: "hoodiesSweatshirts",
  },
  {
    id: 22,
    image: "/Images/HoodiesSweatshirts/sweatshirts (4).jpg",
    price: 200,
    title: "Sweatshirts",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    category: "Old_featured",
    gender: "men",
    productName: "hoodiesSweatshirts",
  },
  {
    id: 23,
    image: "/Images/HoodiesSweatshirts/sweatshirts (5).jpg",
    price: 200,
    title: "Sweatshirts",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    category: "Old_featured",
    gender: "men",
    productName: "hoodiesSweatshirts",
  },
  {
    id: 24,
    image: "/Images/HoodiesSweatshirts/sweatshirts (6).jpg",
    price: 200,
    title: "Sweatshirts",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    category: "Old_featured",
    gender: "men",
    productName: "hoodiesSweatshirts",
  },
];

export default HoodiesSweatshirtAPI;
