const ShoesStoreCardAPI = [
  {
    id: 25,
    image: "/Images/ShoeStore/ShoesStore (1).jpg",
    price: 992,
    title: "NIKE Killshot 2 Leather",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    category: "featured",
    gender: "men",
    productName: "shoeStore",
  },
  {
    id: 26,
    image: "/Images/ShoeStore/ShoesStore (2).jpg",
    price: 999,
    title: "NIKE Killshot 2 Leather",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    category: "new",
    gender: "kids",
    productName: "shoeStore",
  },
  {
    id: 27,
    image: "/Images/ShoeStore/ShoesStore (3).jpg",
    price: 900,
    title: "NIKE Killshot 2 Leather",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    category: "new",
    gender: "women",
    productName: "shoeStore",
  },
  {
    id: 28,
    image: "/Images/ShoeStore/ShoesStore (4).jpg",
    price: 999,
    title: "NIKE Killshot 2 Leather",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    category: "new",
    gender: "kids",
    productName: "shoeStore",
  },
  {
    id: 29,
    image: "/Images/ShoeStore/ShoesStore (5).jpg",
    price: 154,
    title: "NIKE Killshot 2 Leather",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    category: "Old_featured",
    gender: "kids",
    productName: "shoeStore",
  },
  {
    id: 30,
    image: "/Images/ShoeStore/ShoesStore (6).jpg",
    price: 2000,
    title: "NIKE Killshot 2 Leather",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    category: "Old_featured",
    gender: "men",
    productName: "shoeStore",
  },
];

export default ShoesStoreCardAPI;
