const SNKRAPI = [
  {
    id: 31,
    image: "/Images/SNKRS/snkr (1).jpg",
    price: 922,
    title: "Sneakers",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    category: "featured",
    gender: "men",
    productName: "snkr",
  },
  {
    id: 32,
    image: "/Images/SNKRS/snkr (2).jpg",
    price: 999,
    title: "Sneakers",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    category: "new",
    gender: "kids",
    productName: "snkr",
  },
  {
    id: 33,
    image: "/Images/SNKRS/snkr (5).jpg",
    price: 900,
    title: "Sneakers",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    category: "new",
    gender: "",
    productName: "snkr",
  },
  {
    id: 34,
    image: "/Images/SNKRS/snkr (4).jpg",
    price: 999,
    title: "Sneakers",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    category: "new",
    gender: "kids",
    productName: "snkr",
  },
  {
    id: 35,
    image: "/Images/SNKRS/snkr (5).jpg",
    price: 154,
    title: "Sneakers",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    category: "Old_featured",
    gender: "kids",
    productName: "snkr",
  },
  {
    id: 36,
    image: "/Images/SNKRS/snkr (6).jpg",
    price: 200,
    title: "Sneakers",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    category: "Old_featured",
    gender: "men",
    productName: "snkr",
  },
];

export default SNKRAPI;
