const TrousersTigthsAPI = [
  {
    id: 37,
    image: "/Images/Trousers/trousers (1).jpg",
    price: 222,
    title: "Trousers & Tights",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    category: "featured",
    gender: "men",
    productName: "trouserTights",
  },
  {
    id: 38,
    image: "/Images/Trousers/trousers (2).jpg",
    price: 998,
    title: "Trousers & Tights",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    category: "new",
    gender: "kids",
    productName: "trouserTights",
  },
  {
    id: 39,
    image: "/Images/Trousers/trousers (3).jpg",
    price: 900,
    title: "Trousers & Tights",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    category: "new",
    gender: "women",
    productName: "trouserTights",
  },
  {
    id: 40,
    image: "/Images/Trousers/trousers (4).jpg",
    price: 999,
    title: "Trousers & Tights",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    category: "new",
    gender: "kids",
    productName: "trouserTights",
  },
  {
    id: 41,
    image: "/Images/Trousers/trousers (5).jpg",
    price: 1544,
    title: "Trousers & Tights",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    category: "Old_featured",
    gender: "kids",
    productName: "trouserTights",
  },
  {
    id: 42,
    image: "/Images/Trousers/trousers (6).jpg",
    price: 200,
    title: "Trousers & Tights",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    category: "Old_featured",
    gender: "men",
    productName: "trouserTights",
  },
];

export default TrousersTigthsAPI;
